/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tuerca.pos.view;

/**
 *
 * @author mannycalderon
 */
public class AdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnEmpleados = new javax.swing.JButton();
        btnEmpleados.putClientProperty("FlatLaf.style", "arc: 20; iconTextGap: 15; focusWidth: 0");
        btnProductos = new javax.swing.JButton();
        btnProductos.putClientProperty("FlatLaf.style", "arc: 20; iconTextGap: 15; focusWidth: 0");
        btnVentas = new javax.swing.JButton();
        btnVentas.putClientProperty("FlatLaf.style", "arc: 20; iconTextGap: 15; focusWidth: 0");
        btnEmprendedores = new javax.swing.JButton();
        btnEmprendedores.putClientProperty("FlatLaf.style", "arc: 20; iconTextGap: 15; focusWidth: 0");
        btnApartados = new javax.swing.JButton();
        btnApartados.putClientProperty("FlatLaf.style", "arc: 20; iconTextGap: 15; focusWidth: 0");
        btnArqueoCaja = new javax.swing.JButton();
        btnArqueoCaja.putClientProperty("FlatLaf.style", "arc: 20; iconTextGap: 15; focusWidth: 0");
        btnPagoEmprendedores = new javax.swing.JButton();
        btnPagoEmprendedores.putClientProperty("FlatLaf.style", "arc: 20; iconTextGap: 15; focusWidth: 0");
        btnDevolucion = new javax.swing.JButton();
        btnDevolucion.putClientProperty("FlatLaf.style", "arc: 20; iconTextGap: 15; focusWidth: 0");
        btnCorteCaja = new javax.swing.JButton();
        btnCorteCaja.putClientProperty("FlatLaf.style", "arc: 20; iconTextGap: 15; focusWidth: 0");
        btnReportes = new javax.swing.JButton();
        btnReportes.putClientProperty("FlatLaf.style", "arc: 20; iconTextGap: 15; focusWidth: 0");
        jLabel3 = new javax.swing.JLabel();

        setBounds(new java.awt.Rectangle(0, 0, 1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jLabel5.setFont(new java.awt.Font("SF Pro Rounded", 1, 28)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("POS de Venta");

        jLabel2.setFont(new java.awt.Font("SF Pro Rounded", 1, 28)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Aura Tienda Colectiva");

        jPanel1.setLayout(new java.awt.GridLayout(4, 3, 20, 20));

        btnEmpleados.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btnEmpleados.setFont(new java.awt.Font("SF Pro Rounded", 1, 24)); // NOI18N
        btnEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpleados.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("com/tuerca/pos/icons/empleados.svg", 48, 48));
        btnEmpleados.setText("Empleados");
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        jPanel1.add(btnEmpleados);

        btnProductos.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btnProductos.setFont(new java.awt.Font("SF Pro Rounded", 1, 24)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnProductos.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("com/tuerca/pos/icons/productos.svg", 48, 48));
        btnProductos.setText("Gestión Productos");
        jPanel1.add(btnProductos);

        btnVentas.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        btnVentas.setFont(new java.awt.Font("SF Pro Rounded", 1, 24)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnVentas.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("com/tuerca/pos/icons/ventas.svg", 48, 48));
        btnVentas.setText("Venta");
        jPanel1.add(btnVentas);

        btnEmprendedores.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btnEmprendedores.setFont(new java.awt.Font("SF Pro Rounded", 1, 24)); // NOI18N
        btnEmprendedores.setForeground(new java.awt.Color(255, 255, 255));
        btnEmprendedores.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("com/tuerca/pos/icons/emprendedores.svg", 48, 48));
        btnEmprendedores.setText("Gestión Emprendedores");
        jPanel1.add(btnEmprendedores);

        btnApartados.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btnApartados.setFont(new java.awt.Font("SF Pro Rounded", 1, 24)); // NOI18N
        btnApartados.setForeground(new java.awt.Color(255, 255, 255));
        btnApartados.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("com/tuerca/pos/icons/apartados.svg", 48, 48));
        btnApartados.setText("Gestión Apartados");
        jPanel1.add(btnApartados);

        btnArqueoCaja.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        btnArqueoCaja.setFont(new java.awt.Font("SF Pro Rounded", 1, 24)); // NOI18N
        btnArqueoCaja.setForeground(new java.awt.Color(255, 255, 255));
        btnArqueoCaja.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("com/tuerca/pos/icons/arqueocaja.svg", 48, 48));
        btnArqueoCaja.setText("Arqueo de Caja");
        jPanel1.add(btnArqueoCaja);

        btnPagoEmprendedores.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btnPagoEmprendedores.setFont(new java.awt.Font("SF Pro Rounded", 1, 24)); // NOI18N
        btnPagoEmprendedores.setForeground(new java.awt.Color(255, 255, 255));
        btnPagoEmprendedores.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("com/tuerca/pos/icons/pagoemprendedores.svg", 48, 48));
        btnPagoEmprendedores.setText("Pago Emprendedores");
        jPanel1.add(btnPagoEmprendedores);

        btnDevolucion.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        btnDevolucion.setFont(new java.awt.Font("SF Pro Rounded", 1, 24)); // NOI18N
        btnDevolucion.setForeground(new java.awt.Color(255, 255, 255));
        btnDevolucion.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("com/tuerca/pos/icons/devolucion.svg", 48, 48));
        btnDevolucion.setText("Devolución");
        jPanel1.add(btnDevolucion);

        btnCorteCaja.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        btnCorteCaja.setFont(new java.awt.Font("SF Pro Rounded", 1, 24)); // NOI18N
        btnCorteCaja.setForeground(new java.awt.Color(255, 255, 255));
        btnCorteCaja.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("com/tuerca/pos/icons/corte.svg", 48, 48));
        btnCorteCaja.setText("Corte de caja");
        jPanel1.add(btnCorteCaja);

        btnReportes.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        btnReportes.setFont(new java.awt.Font("SF Pro Rounded", 1, 24)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("com/tuerca/pos/icons/reportes.svg", 48, 48));
        btnReportes.setText("Generar Reportes");
        jPanel1.add(btnReportes);

        jLabel3.setFont(new java.awt.Font("SF Pro Rounded", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Administrador:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        // TODO add your handling code here:
        // 1. Buscamos la ventana principal (MainView)
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);

        if (window instanceof com.tuerca.pos.view.MainView main) {
            // 2. Le pedimos que muestre la vista de emprendedores
            // Asegúrate de que "entrepreneur" sea el Card Name que le pusiste en MainView
            main.showView("empleados");
        }
    }//GEN-LAST:event_btnEmpleadosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApartados;
    private javax.swing.JButton btnArqueoCaja;
    private javax.swing.JButton btnCorteCaja;
    private javax.swing.JButton btnDevolucion;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnEmprendedores;
    private javax.swing.JButton btnPagoEmprendedores;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
