/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tuerca.pos.view;

/**
 *
 * @author mannycalderon
 */
public class EmployeePanel extends javax.swing.JPanel {

    /**
     * Creates new form EmployeePanel
     */
    public EmployeePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnEmprendedores = new javax.swing.JButton();
        btnEmprendedores.putClientProperty("FlatLaf.style", "arc: 20");
        btnProductos = new javax.swing.JButton();
        btnProductos.putClientProperty("FlatLaf.style", "arc: 20");
        btnVentas = new javax.swing.JButton();
        btnVentas.putClientProperty("FlatLaf.style", "arc: 20");
        btnPagoEmprendedores = new javax.swing.JButton();
        btnPagoEmprendedores.putClientProperty("FlatLaf.style", "arc: 20");
        btnApartados = new javax.swing.JButton();
        btnApartados.putClientProperty("FlatLaf.style", "arc: 20");
        btnArqueoCaja = new javax.swing.JButton();
        btnArqueoCaja.putClientProperty("FlatLaf.style", "arc: 20");
        btnReportes = new javax.swing.JButton();
        btnReportes.putClientProperty("FlatLaf.style", "arc: 20");
        btnDevolucion = new javax.swing.JButton();
        btnDevolucion.putClientProperty("FlatLaf.style", "arc: 20");
        btnCorteCaja = new javax.swing.JButton();
        btnCorteCaja.putClientProperty("FlatLaf.style", "arc: 20");
        jLabel3 = new javax.swing.JLabel();

        setBounds(new java.awt.Rectangle(0, 0, 1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jLabel5.setFont(new java.awt.Font("SF Pro Rounded", 1, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("POS de Venta");

        jLabel2.setFont(new java.awt.Font("SF Pro Rounded", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Aura Tienda Colectiva");

        jPanel1.setLayout(new java.awt.GridLayout(3, 3, 20, 20));

        btnEmprendedores.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btnEmprendedores.setFont(new java.awt.Font("SF Pro Rounded", 1, 24)); // NOI18N
        btnEmprendedores.setForeground(new java.awt.Color(255, 255, 255));
        btnEmprendedores.setText("Gestión Emprendedores");
        btnEmprendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprendedoresActionPerformed(evt);
            }
        });
        jPanel1.add(btnEmprendedores);

        btnProductos.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btnProductos.setFont(new java.awt.Font("SF Pro Rounded", 1, 24)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnProductos.setText("Gestión Productos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        jPanel1.add(btnProductos);

        btnVentas.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        btnVentas.setFont(new java.awt.Font("SF Pro Rounded", 1, 24)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnVentas.setText("Ventas");
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        jPanel1.add(btnVentas);

        btnPagoEmprendedores.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btnPagoEmprendedores.setFont(new java.awt.Font("SF Pro Rounded", 1, 24)); // NOI18N
        btnPagoEmprendedores.setForeground(new java.awt.Color(255, 255, 255));
        btnPagoEmprendedores.setText("Pago Emprendedores");
        btnPagoEmprendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagoEmprendedoresActionPerformed(evt);
            }
        });
        jPanel1.add(btnPagoEmprendedores);

        btnApartados.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btnApartados.setFont(new java.awt.Font("SF Pro Rounded", 1, 24)); // NOI18N
        btnApartados.setForeground(new java.awt.Color(255, 255, 255));
        btnApartados.setText("Gestión Apartados");
        btnApartados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApartadosActionPerformed(evt);
            }
        });
        jPanel1.add(btnApartados);

        btnArqueoCaja.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        btnArqueoCaja.setFont(new java.awt.Font("SF Pro Rounded", 1, 24)); // NOI18N
        btnArqueoCaja.setForeground(new java.awt.Color(255, 255, 255));
        btnArqueoCaja.setText("Arqueo de Caja");
        btnArqueoCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArqueoCajaActionPerformed(evt);
            }
        });
        jPanel1.add(btnArqueoCaja);

        btnReportes.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        btnReportes.setFont(new java.awt.Font("SF Pro Rounded", 1, 24)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("Generar Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        jPanel1.add(btnReportes);

        btnDevolucion.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        btnDevolucion.setFont(new java.awt.Font("SF Pro Rounded", 1, 24)); // NOI18N
        btnDevolucion.setForeground(new java.awt.Color(255, 255, 255));
        btnDevolucion.setText("Devolución");
        btnDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolucionActionPerformed(evt);
            }
        });
        jPanel1.add(btnDevolucion);

        btnCorteCaja.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        btnCorteCaja.setFont(new java.awt.Font("SF Pro Rounded", 1, 24)); // NOI18N
        btnCorteCaja.setForeground(new java.awt.Color(255, 255, 255));
        btnCorteCaja.setText("Corte de Caja");
        btnCorteCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorteCajaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCorteCaja);

        jLabel3.setFont(new java.awt.Font("SF Pro Rounded", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Usuario:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmprendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprendedoresActionPerformed
        // TODO add your handling code here:
        // 1. Buscamos la ventana principal (MainView)
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);

        if (window instanceof com.tuerca.pos.view.MainView main) {
            // 2. Le pedimos que muestre la vista de emprendedores
            // Asegúrate de que "entrepreneur" sea el Card Name que le pusiste en MainView
            main.showView("entrepreneur");
        }
    }//GEN-LAST:event_btnEmprendedoresActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:
        // 1. Buscamos la ventana principal (MainView)
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);

        if (window instanceof com.tuerca.pos.view.MainView main) {
            // 2. Le pedimos que muestre la vista de emprendedores
            // Asegúrate de que "entrepreneur" sea el Card Name que le pusiste en MainView
            main.showView("products");
        }
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        // TODO add your handling code here:
        // 1. Buscamos la ventana principal (MainView)
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);

        if (window instanceof com.tuerca.pos.view.MainView main) {
            // 2. Le pedimos que muestre la vista de emprendedores
            // Asegúrate de que "entrepreneur" sea el Card Name que le pusiste en MainView
            main.showView("ventas");
        }
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucionActionPerformed
        // TODO add your handling code here:
        // 1. Buscamos la ventana principal (MainView)
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);

        if (window instanceof com.tuerca.pos.view.MainView main) {
            // 2. Le pedimos que muestre la vista de emprendedores
            // Asegúrate de que "entrepreneur" sea el Card Name que le pusiste en MainView
            main.showView("devoluciones");
        }
    }//GEN-LAST:event_btnDevolucionActionPerformed

    private void btnApartadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApartadosActionPerformed
        // TODO add your handling code here:
        // 1. Buscamos la ventana principal (MainView)
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);

        if (window instanceof com.tuerca.pos.view.MainView main) {
            // 2. Le pedimos que muestre la vista de emprendedores
            // Asegúrate de que "entrepreneur" sea el Card Name que le pusiste en MainView
            main.showView("apartados");
        }
    }//GEN-LAST:event_btnApartadosActionPerformed

    private void btnArqueoCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArqueoCajaActionPerformed
        // TODO add your handling code here:
        // 1. Buscamos la ventana principal (MainView)
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);

        if (window instanceof com.tuerca.pos.view.MainView main) {
            // 2. Le pedimos que muestre la vista de emprendedores
            // Asegúrate de que "entrepreneur" sea el Card Name que le pusiste en MainView
            main.showView("arqueo");
        }
    }//GEN-LAST:event_btnArqueoCajaActionPerformed

    private void btnCorteCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorteCajaActionPerformed
        // TODO add your handling code here:
        // 1. Buscamos la ventana principal (MainView)
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);

        if (window instanceof com.tuerca.pos.view.MainView main) {
            // 2. Le pedimos que muestre la vista de emprendedores
            // Asegúrate de que "entrepreneur" sea el Card Name que le pusiste en MainView
            main.showView("corte");
        }
    }//GEN-LAST:event_btnCorteCajaActionPerformed

    private void btnPagoEmprendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoEmprendedoresActionPerformed
        // TODO add your handling code here:
        // 1. Buscamos la ventana principal (MainView)
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);

        if (window instanceof com.tuerca.pos.view.MainView main) {
            // 2. Le pedimos que muestre la vista de emprendedores
            // Asegúrate de que "entrepreneur" sea el Card Name que le pusiste en MainView
            main.showView("pagoEmprendedores");
        }
    }//GEN-LAST:event_btnPagoEmprendedoresActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
        // 1. Buscamos la ventana principal (MainView)
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);

        if (window instanceof com.tuerca.pos.view.MainView main) {
            // 2. Le pedimos que muestre la vista de emprendedores
            // Asegúrate de que "entrepreneur" sea el Card Name que le pusiste en MainView
            main.showView("reportes");
        }
    }//GEN-LAST:event_btnReportesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApartados;
    private javax.swing.JButton btnArqueoCaja;
    private javax.swing.JButton btnCorteCaja;
    private javax.swing.JButton btnDevolucion;
    private javax.swing.JButton btnEmprendedores;
    private javax.swing.JButton btnPagoEmprendedores;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
