/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tuerca.pos.view;

/**
 *
 * @author mannycalderon
 */
public class EmployeePanel extends javax.swing.JPanel {

    /**
     * Creates new form EmployeePanel
     */
    public EmployeePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBounds(new java.awt.Rectangle(0, 0, 1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jLabel5.setFont(new java.awt.Font("SF Pro Rounded", 1, 28)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("POS de Venta");

        jLabel2.setFont(new java.awt.Font("SF Pro Rounded", 1, 28)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Aura Tienda Colectiva");

        jPanel1.setLayout(new java.awt.GridLayout(3, 3, 20, 20));

        jButton1.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jButton1.setFont(new java.awt.Font("SF Pro Rounded", 1, 18)); // NOI18N
        jButton1.setText("Gestión Emprendedores");
        jPanel1.add(jButton1);

        jButton2.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jButton2.setFont(new java.awt.Font("SF Pro Rounded", 1, 18)); // NOI18N
        jButton2.setText("Gestión Productos");
        jPanel1.add(jButton2);

        jButton4.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        jButton4.setFont(new java.awt.Font("SF Pro Rounded", 1, 18)); // NOI18N
        jButton4.setText("Ventas");
        jPanel1.add(jButton4);

        jButton7.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jButton7.setFont(new java.awt.Font("SF Pro Rounded", 1, 18)); // NOI18N
        jButton7.setText("Pago Emprendedores");
        jPanel1.add(jButton7);

        jButton3.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jButton3.setFont(new java.awt.Font("SF Pro Rounded", 1, 18)); // NOI18N
        jButton3.setText("Gestión Apartados");
        jPanel1.add(jButton3);

        jButton5.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        jButton5.setFont(new java.awt.Font("SF Pro Rounded", 1, 18)); // NOI18N
        jButton5.setText("Arqueo de Caja");
        jPanel1.add(jButton5);

        jButton6.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        jButton6.setFont(new java.awt.Font("SF Pro Rounded", 1, 18)); // NOI18N
        jButton6.setText("Generar Reportes");
        jPanel1.add(jButton6);

        jButton8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        jButton8.setFont(new java.awt.Font("SF Pro Rounded", 1, 18)); // NOI18N
        jButton8.setText("Devolución");
        jPanel1.add(jButton8);

        jButton9.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        jButton9.setFont(new java.awt.Font("SF Pro Rounded", 1, 18)); // NOI18N
        jButton9.setText("Corte de Caja");
        jPanel1.add(jButton9);

        jLabel3.setFont(new java.awt.Font("SF Pro Rounded", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Usuario:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(0, 35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
