/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tuerca.pos.view;

/**
 *
 * @author mannycalderon
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        
        // Configuramos el tamaño de la ventana principal
        this.setSize(1280, 720);
        this.setLocationRelativeTo(null);
        
        // Forzamos el nombre de las cartas por código
        getContentPane().add(loginPanel1, "login");
        getContentPane().add(adminPanel2, "admin");
        getContentPane().add(employeePanel2, "employee");
        
        // conectamos el controlador 
        // En el constructor de MainView.java
        com.tuerca.pos.controller.EmpleadoController empController = 
            new com.tuerca.pos.controller.EmpleadoController(
                nuevoEmpleado1,   // Vista de Registro
                editarEmpleado1,  // Vista de Edición (Asegúrate de que este sea el nombre de la variable)
                gestionEmpleados1,// Vista de Gestión
                this              // MainView
            );
        empController.cargarTabla();
        
        com.tuerca.pos.controller.EmprendedorController empreController = 
                new com.tuerca.pos.controller.EmprendedorController(
                        nuevoEmprendedor1,
                        editarEmprendimiento1,
                        gestionEmprendedores1, 
                        this
                );
        empreController.cargarTabla();
        
        // Dentro del constructor de MainView.java
        com.tuerca.pos.controller.ProductoController prodController = 
                new com.tuerca.pos.controller.ProductoController(
                        gestionProductos1,
                        nuevoProducto1,
                        this
                );
        
        showView("login");
    }
    
    public void showView(String viewName) {
        java.awt.CardLayout cl = (java.awt.CardLayout) getContentPane().getLayout();
        cl.show(getContentPane(), viewName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel1 = new com.tuerca.pos.view.LoginPanel();
        employeePanel2 = new com.tuerca.pos.view.EmployeePanel();
        adminPanel2 = new com.tuerca.pos.view.AdminPanel();
        gestionEmprendedores1 = new com.tuerca.pos.view.GestionEmprendedores();
        gestionProductos1 = new com.tuerca.pos.view.GestionProductos();
        ventas1 = new com.tuerca.pos.view.Ventas();
        gestionDevoluciones1 = new com.tuerca.pos.view.GestionDevoluciones();
        gestionApartados1 = new com.tuerca.pos.view.GestionApartados();
        arqueoDeCaja1 = new com.tuerca.pos.view.ArqueoDeCaja();
        corteDeCaja1 = new com.tuerca.pos.view.CorteDeCaja();
        pagoEmprendedores1 = new com.tuerca.pos.view.PagoEmprendedores();
        generarReportes1 = new com.tuerca.pos.view.GenerarReportes();
        gestionEmpleados1 = new com.tuerca.pos.view.GestionEmpleados();
        nuevoEmpleado1 = new com.tuerca.pos.view.NuevoEmpleado();
        editarEmpleado1 = new com.tuerca.pos.view.EditarEmpleado();
        nuevoEmprendedor1 = new com.tuerca.pos.view.NuevoEmprendedor();
        editarEmprendimiento1 = new com.tuerca.pos.view.EditarEmprendimiento();
        nuevoProducto1 = new com.tuerca.pos.view.NuevoProducto();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(loginPanel1, "card2");
        getContentPane().add(employeePanel2, "card3");
        getContentPane().add(adminPanel2, "card4");
        getContentPane().add(gestionEmprendedores1, "entrepreneur");
        getContentPane().add(gestionProductos1, "products");
        getContentPane().add(ventas1, "ventas");
        getContentPane().add(gestionDevoluciones1, "devoluciones");
        getContentPane().add(gestionApartados1, "apartados");
        getContentPane().add(arqueoDeCaja1, "arqueo");
        getContentPane().add(corteDeCaja1, "corte");
        getContentPane().add(pagoEmprendedores1, "pagoEmprendedores");
        getContentPane().add(generarReportes1, "reportes");
        getContentPane().add(gestionEmpleados1, "empleados");
        getContentPane().add(nuevoEmpleado1, "nuevoEmpleado");
        getContentPane().add(editarEmpleado1, "editarEmpleado");
        getContentPane().add(nuevoEmprendedor1, "nuevoEmprendedor");
        getContentPane().add(editarEmprendimiento1, "editarEmprendimiento");
        getContentPane().add(nuevoProducto1, "nuevoProducto");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.tuerca.pos.view.AdminPanel adminPanel2;
    private com.tuerca.pos.view.ArqueoDeCaja arqueoDeCaja1;
    private com.tuerca.pos.view.CorteDeCaja corteDeCaja1;
    private com.tuerca.pos.view.EditarEmpleado editarEmpleado1;
    private com.tuerca.pos.view.EditarEmprendimiento editarEmprendimiento1;
    private com.tuerca.pos.view.EmployeePanel employeePanel2;
    private com.tuerca.pos.view.GenerarReportes generarReportes1;
    private com.tuerca.pos.view.GestionApartados gestionApartados1;
    private com.tuerca.pos.view.GestionDevoluciones gestionDevoluciones1;
    private com.tuerca.pos.view.GestionEmpleados gestionEmpleados1;
    private com.tuerca.pos.view.GestionEmprendedores gestionEmprendedores1;
    private com.tuerca.pos.view.GestionProductos gestionProductos1;
    private com.tuerca.pos.view.LoginPanel loginPanel1;
    private com.tuerca.pos.view.NuevoEmpleado nuevoEmpleado1;
    private com.tuerca.pos.view.NuevoEmprendedor nuevoEmprendedor1;
    private com.tuerca.pos.view.NuevoProducto nuevoProducto1;
    private com.tuerca.pos.view.PagoEmprendedores pagoEmprendedores1;
    private com.tuerca.pos.view.Ventas ventas1;
    // End of variables declaration//GEN-END:variables
}
