/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tuerca.pos.view;

import javax.swing.JButton;

/**
 *
 * @author mannycalderon
 */
public class NuevoEmprendedor extends javax.swing.JPanel {
    /**
     * Creates new form GestionEmprendedores
     */
    public NuevoEmprendedor() {
        initComponents();
        brandNameField.putClientProperty("JTextField.placeholderText", "Introduce el nombre del emprendimiento");
        brandNameField.putClientProperty("JTextField.showClearButton", true);
        
        contactNameField.putClientProperty("JTextField.placeholderText", "Introduce el nombre del emprendedor");
        contactNameField.putClientProperty("JTextField.showClearButton", true);
        
        
        contactPhoneField.putClientProperty("JTextField.placeholderText", "Introduce el número de contacto a 10 digitos");
        contactPhoneField.putClientProperty("JTextField.showClearButton", true);
        
        emailField.putClientProperty("JTextField.placeholderText", "Introduce el correo electronico del emprendedor");
        emailField.putClientProperty("JTextField.showClearButton", true);
        
        rentField.putClientProperty("JTextField.placeholderText", "Introduce la renta mensual (Ej: 400)");
        rentField.putClientProperty("JTextField.showClearButton", true);
        
       // Accedemos al editor interno para poner el placeholder
        javax.swing.JTextField dateEditor = (javax.swing.JTextField) datePicker.getDateEditor().getUiComponent();
        dateEditor.putClientProperty("JTextField.placeholderText", "Selecciona la fecha de contrato");
        dateEditor.putClientProperty("JTextField.showClearButton", true);

        // Opcional: Hacer que no puedan escribir manualmente para evitar errores de formato
        dateEditor.setEditable(false);
    }
    
    // Exponemos los datos
    public String getBrandName() { return brandNameField.getText().trim(); }
    public String getContactName() { return contactNameField.getText().trim(); }
    public String getContactPhone() { return contactPhoneField.getText().trim(); }
    public String getEmail() { return emailField.getText().trim(); }
    public String getRent() { return rentField.getText().trim(); }
    public java.util.Date getFechaSeleccionada() { return datePicker.getDate(); }

    // Exponemos el boton de registro
    public JButton getBtnRegistrar() { return btnRegistrar; }
    public JButton getBtnCancelar() { return btnCancelar;}
    public JButton getBtnBack() { return btnBack;}
    
    // limpiar el formulario
    public void limpiarFormulario(){
        brandNameField.setText("");
        contactPhoneField.setText("");
        contactNameField.setText("");
        emailField.setText("");
        rentField.setText("");
        datePicker.setDate(null); 

        brandNameField.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnBack.putClientProperty("FlatLaf.style", "arc: 13; iconTextGap: 10; focusWidth: 0");
        formularioRegistro = new javax.swing.JPanel();
        formularioRegistro.putClientProperty("FlatLaf.style", "arc: 20");
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        brandNameField = new javax.swing.JTextField();
        brandNameField.putClientProperty("FlatLaf.style", "arc: 20");
        contactPhoneField = new javax.swing.JTextField();
        contactPhoneField.putClientProperty("FlatLaf.style", "arc: 20");
        btnRegistrar = new javax.swing.JButton();
        btnRegistrar.putClientProperty("FlatLaf.style", "arc: 20; iconTextGap: 10; focusWidth: 0");
        btnCancelar = new javax.swing.JButton();
        btnCancelar.putClientProperty("FlatLaf.style", "arc: 20; iconTextGap: 10; focusWidth: 0");
        jLabel10 = new javax.swing.JLabel();
        rentField = new javax.swing.JTextField();
        rentField.putClientProperty("FlatLaf.style", "arc: 20");
        jLabel11 = new javax.swing.JLabel();
        contactNameField = new javax.swing.JTextField();
        contactNameField.putClientProperty("FlatLaf.style", "arc: 20");
        jLabel2 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        emailField.putClientProperty("FlatLaf.style", "arc: 20");
        jLabel12 = new javax.swing.JLabel();
        datePicker = new com.toedter.calendar.JDateChooser();
        datePicker.putClientProperty("FlatLaf.style", "arc: 20");

        jLabel5.setFont(new java.awt.Font("SF Pro Rounded", 1, 28)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Crear un nuevo emprendimiento");

        jLabel3.setFont(new java.awt.Font("SF Pro Rounded", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Usuario: ");

        btnBack.setBackground(java.awt.Color.pink);
        btnBack.setFont(new java.awt.Font("SF Pro Rounded", 0, 13)); // NOI18N
        btnBack.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("com/tuerca/pos/icons/back.svg", 24, 24));
        btnBack.setText("Volver");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        formularioRegistro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Emprendimiento", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SF Pro Rounded", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("SF Pro Rounded", 1, 14)); // NOI18N
        jLabel1.setText("Nombre del emprendimiento:");

        jLabel6.setFont(new java.awt.Font("SF Pro Rounded", 1, 14)); // NOI18N
        jLabel6.setText("Número de teléfono:");

        brandNameField.setFont(new java.awt.Font("SF Pro Rounded", 0, 18)); // NOI18N

        contactPhoneField.setFont(new java.awt.Font("SF Pro Rounded", 0, 18)); // NOI18N

        btnRegistrar.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        btnRegistrar.setFont(new java.awt.Font("SF Pro Rounded", 1, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("com/tuerca/pos/icons/check.svg", 24, 24));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        btnCancelar.setFont(new java.awt.Font("SF Pro Rounded", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("com/tuerca/pos/icons/cancel.svg", 24, 24));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("SF Pro Rounded", 1, 14)); // NOI18N
        jLabel10.setText("Costo de renta mensual:");

        rentField.setFont(new java.awt.Font("SF Pro Rounded", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("SF Pro Rounded", 1, 14)); // NOI18N
        jLabel11.setText("Fecha de inicio");

        contactNameField.setFont(new java.awt.Font("SF Pro Rounded", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("SF Pro Rounded", 1, 14)); // NOI18N
        jLabel2.setText("Emprendedor:");

        emailField.setFont(new java.awt.Font("SF Pro Rounded", 0, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("SF Pro Rounded", 1, 14)); // NOI18N
        jLabel12.setText("Correo electronico:");

        javax.swing.GroupLayout formularioRegistroLayout = new javax.swing.GroupLayout(formularioRegistro);
        formularioRegistro.setLayout(formularioRegistroLayout);
        formularioRegistroLayout.setHorizontalGroup(
            formularioRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formularioRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formularioRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brandNameField)
                    .addGroup(formularioRegistroLayout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(contactNameField)
                    .addComponent(contactPhoneField)
                    .addComponent(emailField)
                    .addComponent(rentField)
                    .addGroup(formularioRegistroLayout.createSequentialGroup()
                        .addGroup(formularioRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(datePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        formularioRegistroLayout.setVerticalGroup(
            formularioRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formularioRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brandNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rentField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(formularioRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(formularioRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(263, 263, 263))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addComponent(formularioRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        // Buscamos la ventana principal
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);

        if (window instanceof com.tuerca.pos.view.MainView main) {
            // Regresamos al panel del empleado (el dashboard de los 9 botones)
            main.showView("entrepreneur"); 
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        // Buscamos la ventana principal
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);

        if (window instanceof com.tuerca.pos.view.MainView main) {
            // Regresamos al panel del empleado (el dashboard de los 9 botones)
            main.showView("entrepreneur"); 
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brandNameField;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JTextField contactNameField;
    private javax.swing.JTextField contactPhoneField;
    private com.toedter.calendar.JDateChooser datePicker;
    private javax.swing.JTextField emailField;
    private javax.swing.JPanel formularioRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField rentField;
    // End of variables declaration//GEN-END:variables
}
